### ISSUE TITLE
Getting chown: invalid user: ‘debian-transmission:www-data’ error

### ISSUE THREAD

**Issue by planecore** [YunoHost-Apps/transmission_ynh#44]
Choose a path for Transmission (default: /torrent): 
Warning: chown: invalid user: ‘debian-transmission:www-data’
Warning: !!
Warning:   transmission's script has encountered an error. Its execution was cancelled.
Warning: !!
Warning: 
Warning: rm: cannot remove ‘/home/yunohost.multimedia/share/Torrents’: No such file or directory
Warning: rm: cannot remove ‘/home/yunohost.multimedia/share/Torrent to download’: No such file or directory
Warning: /usr/share/transmission wasn't deleted because it doesn't exist.
Warning: /var/lib/transmission-daemon wasn't deleted because it doesn't exist.
Warning: The user debian-transmission was not found
Success! The SSOwat configuration has been generated
Error: Installation failed

**Comment by maniackcrudelis** [comment]
Can you show us your complete install log please ?

**Comment by matamn** [comment]
There you go:

root@my:~# yunohost app install -l Torrent transmission --verbose
Downloading...
Extracting...
Done
Checking required packages for transmission...
Choose a domain for Transmission (default: yuno.example.com): 
Choose a path for Transmission (default: /torrent): 
Executing script '/var/cache/yunohost/from_file/transmission_ynh-2687c4b3c405eb98171a938f8c08c23351fb2715/scripts/install'...
+ source _common.sh
+ source /usr/share/yunohost/helpers
+++ run-parts --list /usr/share/yunohost/helpers.d
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/backend ']'
++ . /usr/share/yunohost/helpers.d/backend
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/filesystem ']'
++ . /usr/share/yunohost/helpers.d/filesystem
+++ CAN_BIND=1
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/ip ']'
++ . /usr/share/yunohost/helpers.d/ip
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/mysql ']'
++ . /usr/share/yunohost/helpers.d/mysql
+++ MYSQL_ROOT_PWD_FILE=/etc/yunohost/mysql
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/network ']'
++ . /usr/share/yunohost/helpers.d/network
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/package ']'
++ . /usr/share/yunohost/helpers.d/package
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/print ']'
++ . /usr/share/yunohost/helpers.d/print
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/setting ']'
++ . /usr/share/yunohost/helpers.d/setting
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/string ']'
++ . /usr/share/yunohost/helpers.d/string
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/system ']'
++ . /usr/share/yunohost/helpers.d/system
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/user ']'
++ . /usr/share/yunohost/helpers.d/user
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/utils ']'
++ . /usr/share/yunohost/helpers.d/utils
+ ynh_abort_if_errors
+ set -eu
+ trap ynh_exit_properly EXIT
+ domain=yuno.example.com
+ path_url=/torrent
+ app=transmission
++ ynh_normalize_url_path /torrent
++ local path_url=/torrent
++ test -n /torrent
++ '[' / '!=' / ']'
++ '[' t == / ']'
++ echo /torrent
+ path_url=/torrent
+ ynh_webpath_available yuno.example.com /torrent
+ local domain=yuno.example.com
+ local path=/torrent
+ sudo yunohost domain url-available yuno.example.com /torrent
True
+ ynh_webpath_register transmission yuno.example.com /torrent
+ local app=transmission
+ local domain=yuno.example.com
+ local path=/torrent
+ sudo yunohost app register-url transmission yuno.example.com /torrent
+ ynh_app_setting_set transmission domain yuno.example.com
+ sudo yunohost app setting transmission domain --value=yuno.example.com --quiet
+ ynh_app_setting_set transmission path /torrent
+ sudo yunohost app setting transmission path --value=/torrent --quiet
++ ynh_find_port 9091
++ local port=9091
++ test -n 9091
++ netcat -z 127.0.0.1 9091
++ echo 9091
+ port=9091
+ yunohost firewall allow --no-upnp TCP 9091
+ ynh_app_setting_set transmission port 9091
+ sudo yunohost app setting transmission port --value=9091 --quiet
++ ynh_find_port 51413
++ local port=51413
++ test -n 51413
++ netcat -z 127.0.0.1 51413
++ echo 51413
+ peer_port=51413
+ yunohost firewall allow Both 51413
+ ynh_app_setting_set transmission peer_port 51413
+ sudo yunohost app setting transmission peer_port --value=51413 --quiet
+ ynh_install_app_dependencies transmission-daemon acl
+ local 'dependencies=transmission-daemon acl'
+ local manifest_path=../manifest.json
+ '[' '!' -e ../manifest.json ']'
++ cut -d '"' -f 4
++ grep '\"version\": ' ../manifest.json
+ local version=1.0
+ '[' 3 -eq 0 ']'
+ local dep_app=transmission
+ cat
+ ynh_package_install_from_equivs /tmp/transmission-ynh-deps.control
+ local controlfile=/tmp/transmission-ynh-deps.control
+ ynh_package_is_installed equivs
+ grep -c 'ok installed'
+ dpkg-query -W -f '${Status}' equivs
++ cut '-d ' -f 2
++ grep '^Package: ' /tmp/transmission-ynh-deps.control
+ local pkgname=transmission-ynh-deps
++ cut '-d ' -f 2
++ grep '^Version: ' /tmp/transmission-ynh-deps.control
+ local pkgversion=1.0
+ [[ -z transmission-ynh-deps ]]
+ [[ -z 1.0 ]]
+ ynh_package_update
+ ynh_apt update
+ DEBIAN_FRONTEND=noninteractive
+ sudo apt-get -y -qq update
++ mktemp -d
+ local TMPDIR=/tmp/tmp.O0riPPKJtJ
+ cp /tmp/transmission-ynh-deps.control /tmp/tmp.O0riPPKJtJ/control
+ cd /tmp/tmp.O0riPPKJtJ
+ equivs-build ./control
+ sudo dpkg --force-depends -i ./transmission-ynh-deps_1.0_all.deb
Selecting previously unselected package transmission-ynh-deps.
(Reading database ... 38904 files and directories currently installed.)
Preparing to unpack .../transmission-ynh-deps_1.0_all.deb ...
Unpacking transmission-ynh-deps (1.0) ...
Setting up transmission-ynh-deps (1.0) ...
+ ynh_package_install -f
+ ynh_apt --no-remove -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install -f
+ DEBIAN_FRONTEND=noninteractive
+ sudo apt-get -y -qq --no-remove -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install -f
+ [[ -n /tmp/tmp.O0riPPKJtJ ]]
+ rm -rf /tmp/tmp.O0riPPKJtJ
+ ynh_package_is_installed transmission-ynh-deps
+ grep -c 'ok installed'
+ dpkg-query -W -f '${Status}' transmission-ynh-deps
+ rm /tmp/transmission-ynh-deps.control
+ ynh_app_setting_set transmission apt_dependencies transmission-daemon acl
+ sudo yunohost app setting transmission apt_dependencies --value=transmission-daemon --quiet
+ '[' /torrent = / ']'
+ path_url=/torrent/
+ ynh_add_nginx_config
+ finalnginxconf=/etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ ynh_backup_if_checksum_is_different /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ local file=/etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ local checksum_setting_name=checksum__etc_nginx_conf.d_yuno.example.com.d_transmission.conf
++ ynh_app_setting_get transmission checksum__etc_nginx_conf.d_yuno.example.com.d_transmission.conf
++ sudo yunohost app setting transmission checksum__etc_nginx_conf.d_yuno.example.com.d_transmission.conf --output-as plain --quiet
+ local checksum_value=
+ '[' -n '' ']'
+ sudo cp ../conf/nginx.conf /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ test -n /torrent/
+ local path_url_slash_less=/torrent
+ ynh_replace_string __PATH__/ /torrent/ /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ local delimit=@
+ local match_string=__PATH__/
+ local replace_string=/torrent/
+ local workfile=/etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ match_string=__PATH__/
+ replace_string=/torrent/
+ sudo sed --in-place s@__PATH__/@/torrent/@g /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ ynh_replace_string __PATH__ /torrent/ /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ local delimit=@
+ local match_string=__PATH__
+ local replace_string=/torrent/
+ local workfile=/etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ match_string=__PATH__
+ replace_string=/torrent/
+ sudo sed --in-place s@__PATH__@/torrent/@g /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ test -n yuno.example.com
+ ynh_replace_string __DOMAIN__ yuno.example.com /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ local delimit=@
+ local match_string=__DOMAIN__
+ local replace_string=yuno.example.com
+ local workfile=/etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ match_string=__DOMAIN__
+ replace_string=yuno.example.com
+ sudo sed --in-place s@__DOMAIN__@yuno.example.com@g /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ test -n 9091
+ ynh_replace_string __PORT__ 9091 /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ local delimit=@
+ local match_string=__PORT__
+ local replace_string=9091
+ local workfile=/etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ match_string=__PORT__
+ replace_string=9091
+ sudo sed --in-place s@__PORT__@9091@g /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ test -n transmission
+ ynh_replace_string __NAME__ transmission /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ local delimit=@
+ local match_string=__NAME__
+ local replace_string=transmission
+ local workfile=/etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ match_string=__NAME__
+ replace_string=transmission
+ sudo sed --in-place s@__NAME__@transmission@g /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ test -n ''
+ ynh_store_file_checksum /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ local checksum_setting_name=checksum__etc_nginx_conf.d_yuno.example.com.d_transmission.conf
++ cut '-d ' -f1
++ sudo md5sum /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ ynh_app_setting_set transmission checksum__etc_nginx_conf.d_yuno.example.com.d_transmission.conf c3ec654ac7496b6004ca69071388e987
+ sudo yunohost app setting transmission checksum__etc_nginx_conf.d_yuno.example.com.d_transmission.conf --value=c3ec654ac7496b6004ca69071388e987 --quiet
+ sudo systemctl reload nginx
+ mkdir -p /home/yunohost.transmission/progress /home/yunohost.transmission/completed /home/yunohost.transmission/watched
+ chown -R debian-transmission:www-data /home/yunohost.transmission/
Warning: chown: invalid user: ‘debian-transmission:www-data’
+ ynh_exit_properly
+ local exit_code=1
+ '[' 1 -eq 0 ']'
+ trap '' EXIT
+ set +eu
+ echo -e '!!\n  transmission'\''s script has encountered an error. Its execution was cancelled.\n!!'
+ type -t ynh_clean_setup
+ ynh_die
+ echo ''
+ exit 1
Warning: !!
Warning:   transmission's script has encountered an error. Its execution was cancelled.
Warning: !!
Warning: 
Executing script '/var/cache/yunohost/from_file/transmission_ynh-2687c4b3c405eb98171a938f8c08c23351fb2715/scripts/remove'...
+ source _common.sh
+ source /usr/share/yunohost/helpers
+++ run-parts --list /usr/share/yunohost/helpers.d
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/backend ']'
++ . /usr/share/yunohost/helpers.d/backend
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/filesystem ']'
++ . /usr/share/yunohost/helpers.d/filesystem
+++ CAN_BIND=1
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/ip ']'
++ . /usr/share/yunohost/helpers.d/ip
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/mysql ']'
++ . /usr/share/yunohost/helpers.d/mysql
+++ MYSQL_ROOT_PWD_FILE=/etc/yunohost/mysql
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/network ']'
++ . /usr/share/yunohost/helpers.d/network
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/package ']'
++ . /usr/share/yunohost/helpers.d/package
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/print ']'
++ . /usr/share/yunohost/helpers.d/print
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/setting ']'
++ . /usr/share/yunohost/helpers.d/setting
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/string ']'
++ . /usr/share/yunohost/helpers.d/string
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/system ']'
++ . /usr/share/yunohost/helpers.d/system
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/user ']'
++ . /usr/share/yunohost/helpers.d/user
++ for helper in '$(run-parts --list /usr/share/yunohost/helpers.d 2>/dev/null)'
++ '[' -r /usr/share/yunohost/helpers.d/utils ']'
++ . /usr/share/yunohost/helpers.d/utils
+ app=transmission
++ ynh_app_setting_get transmission domain
++ sudo yunohost app setting transmission domain --output-as plain --quiet
+ domain=yuno.example.com
++ ynh_app_setting_get transmission port
++ sudo yunohost app setting transmission port --output-as plain --quiet
+ port=9091
++ ynh_app_setting_get transmission peer_port
++ sudo yunohost app setting transmission peer_port --output-as plain --quiet
+ peer_port=51413
+ ynh_remove_app_dependencies
+ local dep_app=transmission
+ ynh_package_autopurge transmission-ynh-deps
+ ynh_apt autoremove --purge transmission-ynh-deps
+ DEBIAN_FRONTEND=noninteractive
+ sudo apt-get -y -qq autoremove --purge transmission-ynh-deps
(Reading database ... 38907 files and directories currently installed.)
																																			 Removing transmission-ynh-deps (1.0) ...
																																																							 + grep -q transmission-daemon
+ yunohost service status
+ grep -q '\- 9091$'
+ yunohost firewall list
+ echo 'Close port 9091'
Close port 9091
+ yunohost firewall disallow TCP 9091
The firewall has been reloaded
opened_ports:
	- 22
	- 25
	- 53
	- 80
	- 443
	- 465
	- 587
	- 993
	- 5222
	- 5269
	- 5353
	- 51413
+ grep -q '\- 51413$'
+ yunohost firewall list
+ echo 'Close port 51413'
Close port 51413
+ yunohost firewall disallow Both 51413
The firewall has been reloaded
opened_ports:
	- 22
	- 25
	- 53
	- 80
	- 443
	- 465
	- 587
	- 993
	- 5222
	- 5269
	- 5353
+ ynh_remove_nginx_config
+ ynh_secure_remove /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ local path_to_remove=/etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ local 'forbidden_path= 	/var/www 	/home/yunohost.app'
+ [[  	/var/www 	/home/yunohost.app =~ /etc/nginx/conf\.d/my\.matanmashraki\.com\.d/transmission\.conf ]]
+ [[ /etc/nginx/conf.d/yuno.example.com.d/transmission.conf =~ ^/[[:alnum:]]+$ ]]
+ [[ f = \/ ]]
+ '[' -e /etc/nginx/conf.d/yuno.example.com.d/transmission.conf ']'
+ sudo rm -R /etc/nginx/conf.d/yuno.example.com.d/transmission.conf
+ sudo systemctl reload nginx
++ ynh_app_setting_get transmission backup_core_only
++ sudo yunohost app setting transmission backup_core_only --output-as plain --quiet
+ backup_core_only=
+ '[' -z ']'
+ ynh_secure_remove /home/yunohost.transmission
+ local path_to_remove=/home/yunohost.transmission
+ local 'forbidden_path= 	/var/www 	/home/yunohost.app'
+ [[  	/var/www 	/home/yunohost.app =~ /home/yunohost\.transmission ]]
+ [[ /home/yunohost.transmission =~ ^/[[:alnum:]]+$ ]]
+ [[ n = \/ ]]
+ '[' -e /home/yunohost.transmission ']'
+ sudo rm -R /home/yunohost.transmission
+ rm /home/yunohost.multimedia/share/Torrents
Warning: rm: cannot remove ‘/home/yunohost.multimedia/share/Torrents’: No such file or directory
+ rm '/home/yunohost.multimedia/share/Torrent to download'
Warning: rm: cannot remove ‘/home/yunohost.multimedia/share/Torrent to download’: No such file or directory
+ ynh_secure_remove /usr/share/transmission
+ local path_to_remove=/usr/share/transmission
+ local 'forbidden_path= 	/var/www 	/home/yunohost.app'
+ [[  	/var/www 	/home/yunohost.app =~ /usr/share/transmission ]]
+ [[ /usr/share/transmission =~ ^/[[:alnum:]]+$ ]]
+ [[ n = \/ ]]
+ '[' -e /usr/share/transmission ']'
+ echo '/usr/share/transmission wasn'\''t deleted because it doesn'\''t exist.'
+ ynh_secure_remove /var/lib/transmission-daemon
+ local path_to_remove=/var/lib/transmission-daemon
+ local 'forbidden_path= 	/var/www 	/home/yunohost.app'
Warning: /usr/share/transmission wasn't deleted because it doesn't exist.
Warning: /var/lib/transmission-daemon wasn't deleted because it doesn't exist.
+ [[  	/var/www 	/home/yunohost.app =~ /var/lib/transmission-daemon ]]
+ [[ /var/lib/transmission-daemon =~ ^/[[:alnum:]]+$ ]]
+ [[ n = \/ ]]
+ '[' -e /var/lib/transmission-daemon ']'
+ echo '/var/lib/transmission-daemon wasn'\''t deleted because it doesn'\''t exist.'
+ ynh_system_user_delete debian-transmission
+ ynh_system_user_exists debian-transmission
+ getent passwd debian-transmission
+ echo 'The user debian-transmission was not found'
Warning: The user debian-transmission was not found
Success! The SSOwat configuration has been generated
Error: Installation failed

**Comment by maniackcrudelis** [comment]
The problem here is that `sudo apt-get -y -qq --no-remove -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install -f` should have install the dependencies, and especially transmission ! But it didn't...

Could you told me what version of YunoHost are you using (`yunohost -v`) ?

**Comment by maniackcrudelis** [comment]
Oh !
Then, the first thing to do is to upgrade your YunoHost. The current version is 2.7.14 on jessie.

**Comment by matamn** [comment]
Haha didn’t notice that!
Is there any way to force it to upgrade now instead of the next hour?

**Comment by maniackcrudelis** [comment]
OK, so I have currently no idea why apt doesn't want to install transmission...
Anyway, could you try manually to install it.
`apt install transmission-daemon acl`

**Comment by matamn** [comment]
That's weird, it was already installed. I tried to remove it, but it still doesn't work.

**Comment by maniackcrudelis** [comment]
So did you remove it ? Did the remove works ?
Is the log still the same after you remove it ?

**Comment by matamn** [comment]
Yes, still the same.

**Comment by maniackcrudelis** [comment]
OK...
That's really strange.
Could you try to reinstall transmission. Retry the installation of the package.
And, if it still doesn't work, remove transmission with --purge argument. To be sure, there's nothing left before retrying.

**Comment by alexAubin** [comment]
This issue happened again today, after removing then reinstalling the app, for a user on the chat ... same error : 

```
2019-03-25 19:07:50,299: DEBUG - + chown -R debian-transmission:www-data /home/yunohost.transmission/
2019-03-25 19:07:50,300: WARNING - chown: invalid user: â€˜debian-transmission:www-dataâ€™
```
