### ISSUE TITLE
Setting the download destination

### ISSUE THREAD

**Issue by colmoneill** [YunoHost-Apps/transmission_ynh#64]
Hi, I'm wondering if / how it would be possible to configure the destination of the torrent to a specific path ?

My YNH's install is low storage (on RPI) so if there was a way to define where I torrents get saved to (my HDD which is mounted in the system), it would be amazing. 

Thanks for making the port of the app for YNH !

**Comment by maniackcrudelis** [comment]
You can't currently do that from the web admin.
But, you could do it from the command line, usually by creating a mount bind point of your transmission directory to your hard drive.

**Comment by colmoneill** [comment]
Is there any way of simply changing the destination of the transmission app via the CLI ?
When you say creating a mount bind point, you mean a symlink ? The SD card I use for my install is not huge, I'd like to avoid data being in two places if at all possible !

Cheers !

**Comment by maniackcrudelis** [comment]
A mount bind is a special mount point that mount a directory into another instead of hard drives.

The idea here is to mount a directory from your hard drive into transmission directory. So transmission directory will still be at the same place for transmission, but physically, the directory will be on your hard drive.

It looks like that into your `/etc/fstab`
```
/path/of/the/directory/into/your/harddrive /home/yunohost.transmission  none    bind,default,auto
```

It's like a super symlink. When you'll enter the directory, which stay a simple directory, you'll move directly to your hard drive. It's completely transparent.
Be careful though to empty the directory before, because as soon as the mount bind is active, you can't access the "real" content of the directory.
