### ISSUE TITLE
Transmission includes data in backups... again...

### ISSUE THREAD

**Issue by louisbilliet-acteamit** [YunoHost-Apps/transmission_ynh#65]
Hi,

since last upgrade for this app, transmission include data in its backups, even though backup_core_only is set, resulting in my backup scripts taking all disk space without prior notice. This is quite annoying.

**Comment by billietl** [comment]
Bumping with another account, to be sure not to miss updates on this issue.

**Comment by maniackcrudelis** [comment]
Last change about it is from June 1st (https://github.com/YunoHost-Apps/transmission_ynh/pull/56)

Depending of how you make your backup, you can either use the variable environment `BACKUP_CORE_ONLY` to prevent data to be backup for the time of the following command.
Or replace `backup_core_only` by `do_not_backup_data` into the app config to forbid any backup of the data for this app.

**Comment by billietl** [comment]
I see, but I can't find any announcement :/
I use `yunohost backup create` command to create a backup archive. I have reworked my backup script to not backup transmission, but I think I'll stay there, since it's not the first time this kind of prank happens.

**Comment by maniackcrudelis** [comment]
There was no prank.
As said previously somewhere on the forum this setting has never been intended for that usage. This setting was design to prevent upgrade script to backup data.
Following some issues with the process, we have changed that internal behavior.

But because you weren't the only one to use that setting that way, we have decided to add `do_not_backup_data` which is a setting design to fulfill that kind of backups for users.
